### ISSUE TITLE
We can test the "Wingman AI" use case on a landing page (make.com integration into Builder.io)

### ISSUE THREAD

**Issue by EggDice** [Bobcats-Coding/compd#30]
# Story

As a Bars.com business stakeholder, I connect a make.com workflow to a builder.io page, so I can run experiments using ChatGTP

## Scenarios

```gherkin
Scenario: Run a workflow from Builder.io

When an event is triggered on a page and a make.com action is associated with it 
Then the set workflow is triggered

Scenario: Set content from make.com

When a workflow triggers a builder.io content change
Then the content appears on the page
```

## Tasks

- [ ] Setup a builder.io page 
- [ ] #33
- [ ] Add the make.com component as a builder.io custom component
- [ ] Set content from make.com workflow

**Comment by cassus** [comment]
Andi made an experimental project with OpenAI api .

Not sure what is remaining, closing for now. Feel free to re-open.
